"use client";

import {useEffect,useMemo,useState} from "react";
import {AreaChart,Area,BarChart,Bar,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,ScatterChart,Scatter,XAxis,YAxis,Tooltip,ErrorBar} from "recharts";
import {Cloud,Database,Download,Leaf,Link2,MapPin,Play,RefreshCw,Sparkles,TrendingUp,Layers3,CloudSun,ShieldCheck} from "lucide-react";

type Site={site:string;lat:number;lon:number};
type Row=Record<string,any>;
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const fmt=(n:any,d=1)=>Number(n??0).toLocaleString(undefined,{maximumFractionDigits:d});
function csv(rows:Row[],name:string){if(!rows?.length)return;const keys=Object.keys(rows[0]);const q=(v:any)=>`"${String(v??"").replaceAll('"','""')}"`;const out=[keys.join(","),...rows.map(r=>keys.map(k=>q(r[k])).join(","))].join("\n");const a=document.createElement("a");const url=URL.createObjectURL(new Blob([out],{type:"text/csv"}));a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export default function Home(){
 const [sites,setSites]=useState<Site[]>([]),[selected,setSelected]=useState<string[]>([]),[start,setStart]=useState("2025-01-01"),[end,setEnd]=useState("2025-12-31"),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[profileSite,setProfileSite]=useState("");
 useEffect(()=>{fetch(`${API}/api/sites`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(x=>{setSites(x);setSelected(x.map((s:Site)=>s.site));setProfileSite(x[0]?.site||"")}).catch(()=>setError("FastAPI is not reachable. Start the backend on port 8000."))},[]);
 async function run(){setLoading(true);setError("");try{const r=await fetch(`${API}/api/integrate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sites:selected,start_date:start,end_date:end})});const x=await r.json();if(!r.ok)throw new Error(x.detail||"Integration failed");setData(x);if(!selected.includes(profileSite))setProfileSite(selected[0]||"")}catch(e:any){setError(e?.message||"Integration failed") }finally{setLoading(false)}}
 const meta=data?.meta??{},daily:Row[]=Array.isArray(data?.daily)?data.daily:[],summary:Row[]=Array.isArray(data?.summary)?data.summary:[],logs:Row[]=Array.isArray(data?.logs)?data.logs:[],forecast:Row[]=Array.isArray(data?.forecast)?data.forecast:[],soilProfile:Row[]=Array.isArray(data?.soil_profile)?data.soil_profile:[];
 const monthly=useMemo(()=>{const m=new Map<string,any>();daily.forEach((r:Row)=>{const key=String(r.time??"").slice(0,7);if(!key)return;const o=m.get(key)||{month:key,rain:0,et0:0,tempSum:0,n:0};o.rain+=Number(r.precipitation_sum||0);o.et0+=Number(r.et0_fao_evapotranspiration||0);o.tempSum+=Number(r.temperature_2m_mean||0);o.n++;m.set(key,o)});return [...m.values()].map(o=>({...o,temp:o.n?o.tempSum/o.n:0}))},[daily]);
 const forecastChart=useMemo(()=>forecast.filter(r=>r.site===profileSite).map(r=>({date:String(r.time).slice(0,10),temp:Number(r.temperature_2m_mean||0),rain:Number(r.precipitation_sum||0),et0:Number(r.et0_fao_evapotranspiration||0),balance:Number(r.water_balance_mm||0)})),[forecast,profileSite]);
 const profile=useMemo(()=>soilProfile.filter(r=>r.site===profileSite).map(r=>{const out:any={...r};["sand","silt","clay"].forEach(p=>{const mean=Number(r[`${p}_mean`]??0),lo=Number(r[`${p}_Q0.05`]??mean),hi=Number(r[`${p}_Q0.95`]??mean);out[`${p}_error`]=[Math.max(0,mean-lo),Math.max(0,hi-mean)]});return out}),[soilProfile,profileSite]);
 const totalRain=summary.reduce((a:number,r:Row)=>a+Number(r.rain_mm||0),0),cached=logs.filter(l=>l.from_cache).length;
 const textureCharts=[{key:"sand",title:"Sand",fill:"#84cc16"},{key:"silt",title:"Silt",fill:"#22c55e"},{key:"clay",title:"Clay",fill:"#15803d"}];
 return <main><aside><div className="brand"><div className="brandIcon"><Leaf/></div><div><b>SOIL × WEATHER</b><span>ITD112 LAB 01</span></div></div><div className="asideTitle">Integration controls</div><label>Mindanao sites</label><div className="checks">{sites.map(s=><button key={s.site} className={selected.includes(s.site)?"chip active":"chip"} onClick={()=>setSelected(v=>v.includes(s.site)?v.filter(x=>x!==s.site):[...v,s.site])}>{s.site}</button>)}</div><div className="dates"><div><label>Start</label><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div><label>End</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><button className="run" disabled={loading||!selected.length} onClick={run}>{loading?<RefreshCw className="spin"/>:<Play/>}{loading?"Integrating…":"Run integration"}</button><div className="sideNote"><Sparkles/> Includes depth, uncertainty and 16-day forecast extensions.</div><div className="pipeline"><b>Pipeline</b><span>Inputs → Archive + Forecast → Soil depths → Parse → Join → Analyse → Export</span></div><div className="sources"><b>Data sources</b><span>SoilGrids v2.0 · ISRIC</span><span>Open-Meteo Archive + Forecast</span></div></aside>
 <section className="content"><header className="hero"><div><span className="eyebrow">ITD112 · LABORATORY EXERCISE 1</span><h1>Mindanao Soil × Weather <em>Intelligence</em></h1><p>FastAPI + Next.js environmental integration with historical weather, a 16-day forecast, multi-depth SoilGrids profiles, prediction uncertainty, and reproducible exports.</p></div><div className="orb"><Leaf/></div></header>
 <div className="steps">{[["01","Input",MapPin,"Choose sites and a date range."],["02","Request",Cloud,"Call archive, forecast and soil APIs."],["03","Integrate",Link2,"Join weather with soil estimates."],["04","Analyse",TrendingUp,"Explore Q1–Q6 plus extensions."]].map(([n,t,I,d]:any)=><div className={`step s${n}`} key={n}><div className="stepIcon"><I/></div><span>{n} · WORKFLOW</span><b>{t}</b><p>{d}</p></div>)}</div>
 {error&&<div className="error">{error}</div>}
 {!data&&!loading&&<div className="welcome"><div><Database/><h2>Ready when you are</h2><p>Run the integration. FastAPI handles defensive requests, caching, parsing, unit conversion, multi-depth soil uncertainty and forecast retrieval.</p></div><div className="architecture"><span>Next.js UI</span><i>→</i><span>FastAPI</span><i>→</i><span>Open APIs</span></div></div>}
 {loading&&<div className="loading"><div className="loader"/><h2>Building the integrated dataset</h2><p>Uncached SoilGrids calls pause between sites for fair use. Repeat runs use disk cache; forecast cache refreshes hourly.</p></div>}
 {data&&<><div className="sectionHead"><div><span>INTEGRATION RESULTS</span><h2>Environmental Operations Overview</h2></div><button className="ghost" onClick={run}><RefreshCw/> Refresh</button></div>
 <div className="metrics"><div><span>DAILY RECORDS</span><b>{fmt(meta.daily_rows??daily.length,0)}</b><small>historical site × day</small></div><div><span>SELECTED SITES</span><b>{meta.summary_rows??summary.length}</b><small>joined summaries</small></div><div><span>TOTAL RAINFALL</span><b>{fmt(totalRain)} mm</b><small>historical period</small></div><div><span>CACHE ACTIVITY</span><b>{cached}/{logs.length}</b><small>responses from disk</small></div></div>
 <div className="grid2"><article className="panel"><div className="panelTitle"><div><span>Q1</span><h3>Temperature Over Time</h3></div><small>Monthly mean · all sites combined</small></div><ResponsiveContainer width="100%" height={310}><AreaChart data={monthly}><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#22c55e" stopOpacity={.45}/><stop offset="95%" stopColor="#22c55e" stopOpacity={.03}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Area type="monotone" dataKey="temp" stroke="#15803d" fill="url(#g)" strokeWidth={3}/></AreaChart></ResponsiveContainer></article>
 <article className="panel"><div className="panelTitle"><div><span>Q2</span><h3>Rainfall vs Evaporative Demand</h3></div><small>Monthly totals</small></div><ResponsiveContainer width="100%" height={310}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip/><Legend/><Bar dataKey="rain" name="Rainfall" fill="#22c55e" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></article></div>
 <div className="grid2"><article className="panel"><div className="panelTitle"><div><span>Q4</span><h3>Topsoil Texture</h3></div><small>0–5 cm mean · original analysis</small></div><ResponsiveContainer width="100%" height={320}><BarChart data={summary} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis dataKey="site" type="category" width={110}/><Tooltip/><Legend/><Bar dataKey="sand" stackId="a" fill="#bef264"/><Bar dataKey="silt" stackId="a" fill="#4ade80"/><Bar dataKey="clay" stackId="a" fill="#15803d"/></BarChart></ResponsiveContainer></article>
 <article className="panel"><div className="panelTitle"><div><span>Q5</span><h3>Clay vs Water Balance</h3></div><small>Exploratory relationship</small></div><ResponsiveContainer width="100%" height={320}><ScatterChart><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="clay" name="Clay" unit="%"/><YAxis type="number" dataKey="water_balance_mm" name="Water balance" unit=" mm"/><Tooltip cursor={{strokeDasharray:"3 3"}}/><Scatter data={summary} fill="#16a34a"/></ScatterChart></ResponsiveContainer></article></div>
 <article className="panel full"><div className="panelTitle"><div><span>Q3 + Q6</span><h3>Site Comparison & Geographic Context</h3></div><small>Summary table with coordinates and integrated measures</small></div><div className="tableWrap"><table><thead><tr><th>Site</th><th>Rain (mm)</th><th>ET0 (mm)</th><th>Balance</th><th>Temp °C</th><th>Clay</th><th>SOC</th><th>Coordinates</th></tr></thead><tbody>{summary.map((r:Row)=><tr key={r.site}><td><b>{r.site}</b></td><td>{fmt(r.rain_mm)}</td><td>{fmt(r.et0_mm)}</td><td className={Number(r.water_balance_mm)>=0?"positive":"negative"}>{fmt(r.water_balance_mm)}</td><td>{fmt(r.temp_mean_c)}</td><td>{fmt(r.clay)}</td><td>{fmt(r.soc,2)}</td><td>{r.lat}, {r.lon}</td></tr>)}</tbody></table></div></article>
 <div className="extensionHead"><span></span><h2>Deeper Soil, Uncertainty & Future Weather</h2></div>
 <div className="extensionCards"><div><Layers3/><b>3 soil depths</b><span>0–5 · 5–15 · 15–30 cm</span></div><div><ShieldCheck/><b>90% prediction interval</b><span>Q0.05 · mean · Q0.95</span></div><div><CloudSun/><b>16-day forecast</b><span>Temperature · rain · ET₀</span></div></div>
 <article className="panel full"><div className="panelTitle"><div><span>DEPTH + UNCERTAINTY</span><h3>Soil Texture Down the Profile</h3></div><div className="selectWrap"><label>Profile site</label><select value={profileSite} onChange={e=>setProfileSite(e.target.value)}>{selected.map(s=><option key={s}>{s}</option>)}</select></div></div><p className="note">Bars show the SoilGrids mean. Error bars show the Q0.05–Q0.95 prediction interval, so model uncertainty stays visible rather than being hidden behind a single estimate.</p><div className="textureGrid">{textureCharts.map(t=><div className="miniChart" key={t.key}><h4>{t.title}</h4><ResponsiveContainer width="100%" height={250}><BarChart data={profile} layout="vertical" margin={{left:8,right:28}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" unit="%"/><YAxis dataKey="depth" type="category" width={68}/><Tooltip/><Bar dataKey={`${t.key}_mean`} name={`${t.title} mean`} fill={t.fill} radius={[0,7,7,0]}><ErrorBar dataKey={`${t.key}_error`} direction="x" width={6} stroke="#14532d"/></Bar></BarChart></ResponsiveContainer></div>)}</div></article>
 <article className="panel full forecastPanel"><div className="panelTitle"><div><span>FORECAST EXTENSION</span><h3>Coming 16 Days · {profileSite}</h3></div><small>Open-Meteo forecast alongside the historical archive</small></div><ResponsiveContainer width="100%" height={340}><LineChart data={forecastChart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis yAxisId="left"/><YAxis yAxisId="right" orientation="right"/><Tooltip/><Legend/><Line yAxisId="left" type="monotone" dataKey="temp" name="Mean temp °C" stroke="#15803d" strokeWidth={3} dot={false}/><Line yAxisId="right" type="monotone" dataKey="rain" name="Rain mm" stroke="#65a30d" strokeWidth={2}/><Line yAxisId="right" type="monotone" dataKey="et0" name="ET₀ mm" stroke="#22c55e" strokeWidth={2}/></LineChart></ResponsiveContainer><div className="forecastStats"><div><span>16-DAY RAIN</span><b>{fmt(forecastChart.reduce((a,r)=>a+r.rain,0))} mm</b></div><div><span>16-DAY ET₀</span><b>{fmt(forecastChart.reduce((a,r)=>a+r.et0,0))} mm</b></div><div><span>NET BALANCE</span><b>{fmt(forecastChart.reduce((a,r)=>a+r.balance,0))} mm</b></div></div></article>
 <div className="grid2"><article className="panel"><div className="panelTitle"><div><span>AUDIT</span><h3>API Response Log</h3></div><small>status · cache · timing · payload</small></div><div className="logList">{logs.length?logs.map((l:Row,i:number)=><div className="log" key={i}><div><b>{l.api||"API"}</b><span>{l.label||"Request"}</span></div><strong className={l.from_cache?"cached":"live"}>{l.from_cache?"CACHED":`LIVE ${l.status||200}`}</strong><small>{l.elapsed_ms!=null?`${fmt(l.elapsed_ms)} ms`:"saved copy"} · {fmt(Number(l.bytes||0)/1024)} KB</small></div>):<p className="note">No response logs returned.</p>}</div></article><article className="panel"><div className="panelTitle"><div><span>PROVENANCE</span><h3>Export Reproducible Data</h3></div><small>Original + Extension Datasets</small></div><p className="note">{meta.source_note}</p><div className="downloads"><button onClick={()=>csv(summary,"site_summary.csv")}><Download/> Site Summary</button><button onClick={()=>csv(daily,"integrated_daily.csv")}><Download/> Historical Daily</button><button onClick={()=>csv(forecast,"forecast_16_day.csv")}><Download/> 16-day Forecast</button><button onClick={()=>csv(soilProfile,"soil_profile_uncertainty.csv")}><Download/> Soil Profile</button></div></article></div></>}
 </section></main>
}
